name: build

on:
  push:
    branches: [main]

  pull_request:
    branches: [main]

  workflow_dispatch:

jobs:
  build_and_test:
    name: Build & test overload.js on ${{ matrix.os }} with ${{ matrix.compiler }}.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        include:
          - os: ubuntu-latest
            compiler: g++-latest
            target: Linux

          - os: macos-latest
            compiler: g++-latest
            target: Macos

          - os: windows-latest
            compiler: cl
            target: Windows

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Add msbuild to PATH
        if: ${{ matrix.os == 'windows-latest' }}
        uses: microsoft/setup-msbuild@v1.1

      - name: Use MSVC Developer command line (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install necessary packages (Linux)
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: sudo apt-get update && sudo apt-get install libwebkit2gtk-4.0-dev libssl-dev -y

      - name: Configure
        run: mkdir build && cmake -Bbuild -DCMAKE_BUILD_TYPE=Release

      - name: Compile a release build of overload.js (Windows)
        if: ${{ matrix.os == 'windows-latest' }}
        run: msbuild build\overload_js.sln -m /property:Configuration=Release

      - name: Compile a release build of overload.js (Linux and MacOS)
        if: ${{ matrix.os != 'windows-latest' }}
        run: make -C build/ -j4
